### ISSUE TITLE
Error while calling json data ?ajax=pendingTasks&format=json

### ISSUE THREAD

**Issue by rottenCoder** [Josh5/unmanic#106]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/automator/webserver/main.py", line 59, in get
    self.handle_ajax_call(self.get_query_arguments('ajax')[0])
  File "/var/www/automator/webserver/main.py", line 79, in handle_ajax_call
    self.write(json.dumps(self.get_pending_tasks()))
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Task' is not JSON serializable

**Comment by Josh5** [comment]
This is not enough information.
What build is this error on?
Is this error showing on the latest release?

Please provide more information.

**Comment by rottenCoder** [comment]
unmanic-0.0.1-beta7

**Comment by Josh5** [comment]
Is the error showing up on the latest release?

**Comment by Josh5** [comment]
This issue is no longer valid. Ajax endpoint retired
