### ISSUE TITLE
unManic incompatible with latest peewee version

### ISSUE THREAD

**Issue by itimpi** [Josh5/unmanic#157]
I have a Raspberry Pi system that has the latest version of peewee (3.14.1) installed and it appears that unManic is not compatible with this version.   It worked fine on this system with an older version of PeeWee.

UnManic version: 0.0.2

Manual installation

**Comment by Josh5** [comment]
What error are you receiving to indicate that it is not compatible?

**Comment by itimpi** [comment]
I guess I assumed pewee as that is the only difference  I know about in installed software between the system that works and the one that does not.  There are also lots of references to peewee when I issue the unmanic command as I get

unmanic
Starting migrations
There is nothing to migrate
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.overwrite_additional_ffmpeg_options

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/config.py", line 200, in import_settings_from_db
    self.settings = db_settings.select().limit(1).get()
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 6807, in get
    return clone.execute(database)[0]
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 1957, in execute
    return self._execute(database)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2129, in _execute
    cursor = database.execute(self)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3112, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/pi/.local/lib/python3.7/site-packages/playhouse/sqliteq.py", line 249, in execute_sql
    return self._execute(sql, params, commit=commit)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.overwrite_additional_ffmpeg_options

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/unmanic", line 11, in <module>
    load_entry_point('unmanic==0.0.2', 'console_scripts', 'unmanic')()
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/service.py", line 403, in main
    service.run()
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/service.py", line 388, in run
    self.start_threads()
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/service.py", line 338, in start_threads
    settings = config.CONFIG()
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/config.py", line 92, in __init__
    self.import_settings_from_db()
  File "/home/pi/.local/lib/python3.7/site-packages/unmanic-0.0.2-py3.7.egg/unmanic/config.py", line 203, in import_settings_from_db
    self.settings = db_settings.create()
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 6292, in create
    inst.save(force_insert=True)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 6499, in save
    pk = self.insert(**field_dict).execute()
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 1957, in execute
    return self._execute(database)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2707, in _execute
    return super(Insert, self)._execute(database)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2443, in _execute
    return self.handle_result(database, cursor)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2716, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3187, in last_insert_id
    return cursor.lastrowid
  File "/home/pi/.local/lib/python3.7/site-packages/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "/home/pi/.local/lib/python3.7/site-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/home/pi/.local/lib/python3.7/site-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.7/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: table settings has no column named overwrite_additional_ffmpeg_options

**Comment by itimpi** [comment]
It looks like the issue is not pewee but some incompatibility with older unmanic configurations.

I removed the .unmanic folder and its contents from my home folder.  When I now issued the unmanic command it started up successfully without an error (but obviously with default configuration).  Hopefully that might allow you to pin down why the error occurred in the first place so that you can avoid others encountering this issue.
